### ISSUE TITLE
upload resume website screenshots

### ISSUE THREAD

**Issue by angelsoft-tech** [angelsoft-tech/resume-website-template-unfold#2]
## screenshots
please upload some screenshots of resume website so that users can see the ui of template.

**Comment by chenkang-secret** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/117030576/206891580-38868db8-2ca6-4871-9ba1-b6fbbe081dde.png)
![Screenshot_5](https://user-images.githubusercontent.com/117030576/206891622-ca27bae5-cde2-4456-8786-5cc137811b2d.png)
![Screenshot_2](https://user-images.githubusercontent.com/117030576/206891624-569f1771-d4ef-4b12-b02e-04ed4839113a.png)
